CREATE OR REPLACE TABLE PRODUCT_DB.DW_C_PRODUCT.PRODUCTS( --Target table
    PRODUCT_ID NUMBER(4,0) NOT NULL,
    PRODUCT_NAME VARCHAR,
    PRODUCT_DESCRIPTION VARCHAR,
    PRODUCT_EAN NUMBER(13,0), 
    PRODUCT_UPC NUMBER(12,0), 
    NET_PRICE NUMBER(5,2), 
    TAXES NUMBER(5,2),
    PRICE_INC_TAX NUMBER(5,2),
    CREATED_TS TIMESTAMP_LTZ,
    DW_CREATE_TS TIMESTAMP_LTZ,
    DW_LAST_UPDATE_TS TIMESTAMP_LTZ,
    DW_SOURCE_NM VARCHAR,
    DW_FIRST_EFFECTIVE_DT DATE,
    DW_LAST_EFFECTIVE_DT DATE,
    DW_CURRENT_VERSION_IND BOOLEAN,
    DW_LOGICAL_DELETE_IND BOOLEAN,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);
