CREATE DATABASE IF NOT EXISTS PRODUCT_DB;
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_APPL; -- STAGE / SP / STREAM
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_R_PRODUCT; -- INTEGRATION / REFINED TABLE
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_TEMP; -- TRANSIENT LAYER / DATA TRANSFER
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_C_PRODUCT; -- TARGET
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_VIEWS; -- BUISNESS VIEWS
CREATE SCHEMA IF NOT EXISTS PRODUCT_DB.DW_EXCEPTION; -- BUISNESS VIEWS
ALTER ACCOUNT SET TIMEZONE = 'UTC';