CREATE OR REPLACE TABLE PRODUCT_DB.DW_R_PRODUCT.PRODUCTS(  -- create integration table / refined table with raw data type varchar
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    PRODUCT_DESCRIPTION VARCHAR,
    PRODUCT_EAN VARCHAR, 
    PRODUCT_UPC VARCHAR, 
    NET_PRICE VARCHAR, 
    TAXES VARCHAR,
    PRICE_INC_TAX VARCHAR,
    CREATED_TS VARCHAR,
    DW_CREATE_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    DW_SOURCE_NM VARCHAR
);